kind: Pod
apiVersion: v1
metadata:
  name: csi-app
spec:
  containers:
    - name: readme-app
      image: busybox
      command: [ "sleep", "1000000" ]
      volumeMounts:
        - mountPath: "/data"
          name: myvolume
  volumes:
    - name: myvolume
      persistentVolumeClaim:
        claimName: csi-utho-pvc